services:
  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - v_db:/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/data
    ports:
      - "5432:5432"
    container_name: db
  backend:
    image: node
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - ./backend:/home/node/app
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "3000:3000"
    container_name: backend
    working_dir: /home/node/app
    user: node
    entrypoint: ["bash" , "-c" , "npm install && npm run start:dev"]
  frontend:
    image: node
    restart: on-failure
    volumes:
      - ./frontend:/home/node/app
    ports:
      - '5173:5173'
    container_name: frontend
    working_dir: /home/node/app
    depends_on:
      - backend
    user: node  
    entrypoint: ["bash" , "-c" , "npm install && npm run dev"]

networks:
  transcendence:
    driver: bridge

volumes:
  v_db:
    driver_opts:
      type: none
      o: bind
      device: ${DB_VOL_LOC}